package model;

// Generated 27-feb-2015 10:59:16 by Hibernate Tools 3.4.0.CR1

/**
 * Answers generated by hbm2java
 */
public class Answers implements java.io.Serializable {

	private int id;
	private Questions questions;
	private String text;

	public Answers() {
	}

	public Answers(int id) {
		this.id = id;
	}

	public Answers(int id, Questions questions, String text) {
		this.id = id;
		this.questions = questions;
		this.text = text;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
