package model;

// Generated 18-feb-2015 14:10:29 by Hibernate Tools 3.4.0.CR1

/**
 * Answers generated by hbm2java
 */
public class Answers implements java.io.Serializable {

	private byte id;
	private Questions questions;
	private String text;

	public Answers() {
	}

	public Answers(byte id) {
		this.id = id;
	}

	public Answers(byte id, Questions questions, String text) {
		this.id = id;
		this.questions = questions;
		this.text = text;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
