package model;

// Generated 18-feb-2015 14:10:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
@SuppressWarnings("serial")
public class Questions implements java.io.Serializable {

	private Byte id;
	private String text;
	@SuppressWarnings("rawtypes")
	private Set answerses = new HashSet(0);

	public Questions() {
	}

	public Questions(String text, Set answerses) {
		this.text = text;
		this.answerses = answerses;
	}

	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Set getAnswerses() {
		return this.answerses;
	}

	public void setAnswerses(Set answerses) {
		this.answerses = answerses;
	}

}
